### ISSUE TITLE
incorrect move import with css modules

### ISSUE THREAD

**Issue by radziksh** [asvetliakov/move-imports#10] opened 2018-02-08 13:25 UTC
Hi @asvetliakov , I have this problem: we use `css-modules` and `typed-css-modules` in the project. When I rename the `tsx` file, the link to the `css` file is renamed and this is unexpected behavior.

inside `index.tsx` before renaming:
```typescript
import * as styles from "./index.css";
```

inside `index.tsx` after renaming to `container.tsx`:
```typescript
// index.css import is changed to container.tsx although it should not have changed
import * as styles from "./container.tsx"; 
```

folder structure before renaming:
```
index.tsx
index.css
index.css.d.ts
```
folder structure after renaming:
```
container.tsx
index.css
index.css.d.ts
```

link to typed-css-modules: https://github.com/Quramy/typed-css-modules

But in any case, the great extension preserving us a lot of time!

**Comment by asvetliakov** [comment] 2018-02-12 02:27
Thanks for the report, this is duplicate of #8 

I'm looking into issues over the extension along with some refactoring, 🐻  with me a little more

**Closed as completed by asvetliakov** 2018-02-12 02:27 UTC
